# TravelGuard — Data Sources Configuration
# 
# This file defines all the sources the system pulls data from.
# To add a new source, just add an entry here — no code changes needed.
#
# Tier 1: Cheap sources (poll every 2 hours)
# Tier 2: LLM analysis (runs every 12 hours)
# Tier 3: Reserved for future Scout agent

# ============================================================================
# GLOBAL SOURCES (apply to all countries)
# ============================================================================

global_base:
  - name: "US State Department Travel Advisories"
    type: scrape
    url: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html"
    tier: 1
    refresh_hours: 2
    
  - name: "UK FCDO Travel Advice"
    type: scrape
    url: "https://www.gov.uk/foreign-travel-advice"
    tier: 1
    refresh_hours: 2
    
  - name: "WHO Health Alerts"
    type: api
    url: "https://www.who.int/emergencies/disease-outbreak-news"
    tier: 1
    refresh_hours: 2

global_identity:
  jewish_israeli:
    - name: "Israeli NSC Travel Warnings"
      type: scrape
      url: "https://www.gov.il/he/departments/dynamiccollectors/travel-warnings-nsc"
      tier: 1
      refresh_hours: 2

# ============================================================================
# ISRAEL — Country-Specific Sources
# ============================================================================

israel:
  base:
    - name: "Israel Red Alert Feed"
      type: api
      url: "https://www.oref.org.il/WarningMessages/alert/alerts.json"
      tier: 1
      refresh_hours: 2
      
    - name: "Times of Israel RSS"
      type: rss
      url: "https://www.timesofisrael.com/feed/"
      tier: 1
      refresh_hours: 2

# ============================================================================
# NETHERLANDS — Country-Specific Sources
# ============================================================================

netherlands:
  base:
    - name: "NOS News RSS"
      type: rss
      url: "https://feeds.nos.nl/nosnieuwsalgemeen"
      tier: 1
      refresh_hours: 2
      
    - name: "NU.nl RSS"
      type: rss
      url: "https://www.nu.nl/rss/Algemeen"
      tier: 1
      refresh_hours: 2
      
    - name: "NL-Alert"
      type: scrape
      url: "https://actueel.nl-alert.nl/alerts/"
      tier: 1
      refresh_hours: 2
      
    - name: "NCTV Threat Assessments"
      type: scrape
      url: "https://www.nctv.nl/onderwerpen/dreigingsbeeld-terrorisme-nederland"
      tier: 1
      refresh_hours: 2
  
  identity:
    jewish_israeli:
      - name: "CIDI Antisemitism Monitor"
        type: scrape
        url: "https://www.cidi.nl/antisemitisme/"
        tier: 1
        refresh_hours: 2
